# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Information Geometry in Machine Learning"
title_separator          : "-"
name                     : "Information Geometry in ML"
description              : "Blog website for Information Geometry in ML."
url                      : "" #http://127.0.0.1:4000  the base hostname & protocol for your site
baseurl                  : "" # the subpath of your site, e.g. "/blog"
host_url                 : "informationgeometryML.github.io"
repository               : "informationgeometryML/informationgeometryML.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  endpoint               : "https://staticman-yorkerlin.herokuapp.com/v2/entry/"
  allowedFields          : #['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : # "New comment."
  filename               : # comment-{@timestamp}
  format                 : # "yaml"
  moderation             : false
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey              : "6LcXW7McAAAAAH2V0NEG55ZboBkl3SPL4gQFO5dU"
  secret               : "lD5HGm9uOMTAQ2Kim07Ooijx7QtPG1jom+6aZKMA4s3qhHipnbfxuW5yVAVy4UL5XNnuEYg3OQHxF3xznQ/PlcyQXSGbLIBheEKbIO78jP/iEEhUlyXIwg1VbVyie2ux7GmxRA2DfA6GGD2rWcIChoR4l4ZBAaFp1b8duXA/z4EGCxTbNntIjGDm5NYQ9xCbtG4SS3gRe39dww6oUEtzlcX4R81srC0HXk1dd4NB/16K1e//BZW/I8OeDFwKVtBPPgXO53czozYxxEEtJhexHWTv8/F1E4iR5FDCpb7Y7e1wGxhl0Cma7rQlauOZeOf/UXtMw4JdoyTIcDKTitVCwhiMWUW9g4r8srOJHv3J078RhdMV55FHcIshc9kxmKshjT+vOmsA9vs3Hqlwp9sMQ5EYQRdvb60227HrqzRxhgM/QA4gb0sOS0rwOpnj1L4j3+24wW6NfPL900pK74Jxl5MgtzzGMLsXKtSvi/JI+ikEjjBWgPM74+pPwlQxzK/zXUeRAFmjlRxpLwWbvbQjz9cO/i2mFuuFcGOqVegLue+aPyhfLLLYM7XZl8CzS+Uz8sCAet6Zu+Ooc2HClJFqXY1qOJ/dKUEQ3TPRXoUkY/rU5nUzwmrQTPaBOJJCk4d3UWQzhuwpXlZLSRXmDrdFu4sQKfA7y3dbw61FZGQ0mJE="
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Wu Lin,<br>Frank Nielsen,<br>Emtiyaz Khan,<br>Mark Schmidt"
  avatar           : #"/img/biopic.jpg"# path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Blog posts about informaion geometry in machine learning"
  googlescholar    : #
  cv               : # "/files/cv.pdf"
  home             : "/" # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           :  "informationgeometryML"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (t
  tumblr           :
  twitter          : # ""
  vine             :
  weibo            :
  xing             :
  youtube          : #
  email            : "informationgeometryML@gmail.com"
  location         : #

after_footer_scripts:
  - /assets/js/custom.js
  - /assets/js/translations.js
  - /assets/js/math-code.js

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "America/Vancouver"



# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  #- jekyll-scholar

#scholar:
  #style: custom
  #source: _bibliography
  #bibliography_list_tag: p
  #bibliography_item_tag: p
  #bibtex_filters:
    #- latex

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: mywide
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: false
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  #talks:
    #output: true
    #permalink: /:collection/:path/



news_limit: 5
